#!/usr/bin/env bash
# Build the app for the connected iPhone, pointed at the backend on this Mac, then install and
# launch it. See docs/runbook.md §12.
#
#   ./device.sh                  the first connected iPhone
#   PARKING_DEVICE=<id> ./device.sh
#
# On a phone, localhost is the phone, so the app is built to reach this Mac by its local
# network name (http://<LocalHostName>.local:8080). The address and the backend's window hour
# are written into the build, so the app works when opened from the home screen, where
# Xcode's scheme environment does not apply. Debug builds only: a release build refuses
# plaintext whatever it is given.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DERIVED="$ROOT/.build/DerivedData"

[[ -f "$ROOT/Config/Local.xcconfig" ]] || {
  echo "Copy Config/Local.xcconfig.example to Config/Local.xcconfig and set DEVELOPMENT_TEAM." >&2
  exit 1
}

curl -sf -o /dev/null http://localhost:8080/actuator/health \
  || { echo "The backend is not up on :8080: make backend-now" >&2; exit 1; }
HOUR="$(ps -o command= -p "$(lsof -tnP -iTCP:8080 -sTCP:LISTEN | head -1)" | grep -oE 'window-hour=[0-9]+' | cut -d= -f2)"
HOUR="${HOUR:-20}"
HOST="$(scutil --get LocalHostName).local"
URL="http://$HOST:8080"

# Written for Xcode builds too: pressing Run passes none of this on the command line, so the
# build would otherwise fall back to localhost, which on the phone is the phone. The sdk
# condition keeps simulator builds on localhost.
{
  echo "// Generated by scripts/device.sh on $(date '+%Y-%m-%d %H:%M'). Do not edit; rerun make device-config."
  echo "PARKING_BASE_URL[config=Debug][sdk=iphoneos*] = http:/\$()/$HOST:8080"
  echo "PARKING_WINDOW_HOUR[config=Debug][sdk=iphoneos*] = $HOUR"
} > "$ROOT/Config/Device.xcconfig"
echo "==> Config/Device.xcconfig: $URL, window hour $HOUR (Xcode device builds use it too)"
[[ "${1:-}" == "--config-only" ]] && exit 0

DEVICES_JSON="$(mktemp)"
xcrun devicectl list devices --json-output "$DEVICES_JSON" > /dev/null 2>&1 || true
DEVICE="${PARKING_DEVICE:-$(python3 -c '
import json, sys
for device in json.load(open(sys.argv[1]))["result"]["devices"]:
    if (device.get("hardwareProperties", {}).get("deviceType") == "iPhone"
            and device.get("connectionProperties", {}).get("tunnelState") == "connected"):
        print(device["identifier"]); break
' "$DEVICES_JSON")}"
rm -f "$DEVICES_JSON"
[[ -n "$DEVICE" ]] || { echo "No connected iPhone. Plug it in, unlock it, and trust this Mac." >&2; exit 1; }

echo "==> building for the iPhone: $URL, window hour $HOUR"
xcodebuild -project "$ROOT/Parking.xcodeproj" -scheme Parking -configuration Debug \
  -destination "generic/platform=iOS" -derivedDataPath "$DERIVED" -allowProvisioningUpdates \
  build > "$ROOT/.build/device-build.log" 2>&1 \
  || { grep -E "error:" "$ROOT/.build/device-build.log" | head -5; echo "Build failed; see .build/device-build.log" >&2; exit 1; }

APP="$DERIVED/Build/Products/Debug-iphoneos/Parking.app"
echo "==> installing on $DEVICE"
xcrun devicectl device install app --device "$DEVICE" "$APP" > /dev/null
echo "==> launching"
xcrun devicectl device process launch --device "$DEVICE" com.vncdc.parking > /dev/null
echo "==> on the phone: allow Local Network access when asked, then sign in."
echo "    The phone must be able to reach $HOST (same Wi-Fi, or this Mac on the phone's hotspot)."
